/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Moon
 */
public class GUI_RegistrarEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form GUI_RegistrarEstudiante
     */
    public GUI_RegistrarEstudiante() {
        initComponents();
    }
    
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String [2];
        
        arreglo[0]=this.jt_Carnet.getText();
        arreglo[1]=this.jt_Nombre.getText();
               
        return arreglo;
    }
    
    public String devolverCarnet()
    { 
        return this.jt_Carnet.getText();
    }
    
    public String devolverNombre()
    {
        return this.jt_Nombre.getText();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_Nombre.setText(arreglo[0]);
    }
    public void modifico()
    {
        this.jt_Nombre.setText("");
        this.jt_Carnet.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Carnet = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jt_Carnet = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jl_Carnet.setText("Carnet");
        add(jl_Carnet);
        jl_Carnet.setBounds(30, 30, 90, 25);

        jl_Nombre.setText("Nombre");
        add(jl_Nombre);
        jl_Nombre.setBounds(30, 80, 90, 20);

        jt_Carnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_CarnetActionPerformed(evt);
            }
        });
        add(jt_Carnet);
        jt_Carnet.setBounds(120, 30, 177, 33);
        add(jt_Nombre);
        jt_Nombre.setBounds(120, 80, 177, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TareaProgra2.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 130);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_CarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CarnetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jl_Carnet;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JTextField jt_Carnet;
    private javax.swing.JTextField jt_Nombre;
    // End of variables declaration//GEN-END:variables
}
